apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: rsapp
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: my-rsapp
  template:
    metadata:
      name: rsapp
      labels:
        app: my-rsapp
    spec:
      containers:
        - name: app
          image: ichte/swarmtest:node
          resources:
            limits:
              memory: "120Mi"
              cpu: "100m"
          ports:
            - containerPort: 8085
