apiVersion: v1
kind: Pod
metadata:
  name: advanced-pod
  labels:
    app: advanced-app
    tier: backend
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 1
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      resources:  # Thêm phần giới hạn tài nguyên
        requests:
          memory: "64Mi"  # Tài nguyên yêu cầu tối thiểu
          cpu: "250m"
        limits:
          memory: "128Mi"  # Giới hạn tài nguyên tối đa
          cpu: "500m"
