apiVersion: v1
kind: Pod
metadata:
  name: emphemeral-volume-example
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep","36000"]
    volumeMounts:
      - name: emphemeral-volume
        mountPath: /test
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name : emphemeral-volume
      emptyDir: {}  
    
