apiVersion: v1
kind: Pod
metadata:
  name: pod-ubuntu
  namespace: dev
  labels: 
    app: my-app
spec:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: ubuntu-container
      image: ubuntu
      command: ["/bin/bash", "-c", "sleep 3600"]
      ports:  
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
