apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-role
  namespace: default
rules:
  - apiGroups: [""]  # Core API group
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]  # Apps API group
    resources: ["deployments"]
    verbs: ["get", "list"]
